sonar.projectKey=simanis-inventory-system
sonar.projectName=SIMANIS - Sistem Manajemen Inventaris & Order
sonar.projectVersion=1.0.0

sonar.sources=src,public
sonar.tests=tests
sonar.sourceEncoding=UTF-8
sonar.php.version=8.2

# Exclusions for 3rd party assets and database scripts
sonar.exclusions=vendor/**,database/**,docs/**,public/assets/login-bg.jpg
sonar.test.inclusions=tests/**/*Test.php
sonar.coverage.exclusions=**/*
